# **Mounting Drive and Importing Libraries**
- Mounting the google drive to access data
- Import all libraries for data analysis

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Use this instead
BASE_DIR = os.getcwd()
DATA_DIR = os.path.join(BASE_DIR, "Data")
os.makedirs(DATA_DIR, exist_ok=True)

In [ ]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

# **Importing Data and Data Cleaning**
- Import data for data cleaning
- data inspection and removal of columns
- Changing data types

In [ ]:
#load lyft data
lyft_path = os.path.join(DATA_DIR, "clean/baywheels_eb_20_25.csv")
lyft_data = pd.read_csv(lyft_path)

In [ ]:
#turn into a geodataframe
lyft_data = pd.read_csv(lyft_path)

In [ ]:
#everything is in working order
lyft_data

,field_1,ride_id,bike_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,...,end_city,year,month,weekday,start_hour,end_hour,trip_duration,bart_trip,day_type,round_trip
0,0,DEED2D13D366AB2E,classic,Market St at 45th St,OK-E2,Market St at 45th St,OK-E2,37.834174,-122.272968,37.834174,...,Oakland,2020,5,5,14,15,54.08,Non-BART,Weekend,True
1,2,26A768EB3AF5366C,classic,El Embarcadero at Grand Ave,OK-I9,Telegraph Ave at 19th St,OK-K5-1,37.808847,-122.249679,37.8087021,...,Oakland,2020,5,6,18,18,11.88,Non-BART,Weekend,False
2,3,B6C8C77A229092B3,classic,Haste St at College Ave,BK-E10,West St at University Ave,BK-D4,37.86641794050319,-122.25379943847656,37.86996670760404,...,Berkeley,2020,5,0,3,4,11.42,Non-BART,Weekday,False
3,5,8C233FDE4753CFBB,classic,El Embarcadero at Grand Ave,OK-I9,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,37.8088479,...,Oakland,2020,5,0,8,8,27.12,Non-BART,Weekday,True
4,6,56AF44144ED81C62,classic,El Embarcadero at Grand Ave,OK-I9,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,37.8088479,...,Oakland,2020,5,0,17,18,44.97,Non-BART,Weekday,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952656,980710,99A8D0EF7E5E62D1,electric,Broadway at 30th St,OK-H5,California St at University Ave,BK-D5,37.8193814,-122.2619284,37.86972662872833,...,Berkeley,2025,12,6,15,16,18.54,Non-BART,Weekend,False
952657,980712,E5192258165E74EB,electric,California St at University Ave,BK-D5,California St at University Ave,BK-D5,37.86972662872833,-122.27938914547282,37.86972662872833,...,Berkeley,2025,12,4,19,19,11.12,Non-BART,Weekday,True
952658,980713,E6496153DC9385DC,classic,Russell St at College Ave,BK-G10,California St at University Ave,BK-D5,37.8584732,-122.2532529,37.86972662872833,...,Berkeley,2025,12,6,4,4,14.83,Non-BART,Weekend,False
952659,980714,A21D1266F4804FC6,electric,Russell St at College Ave,BK-G10,California St at University Ave,BK-D5,37.8584732,-122.2532529,37.86972662872833,...,Berkeley,2025,12,6,10,10,10.41,Non-BART,Weekend,False
952660,980715,095E1EF0F10BEB44,electric,Russell St at College Ave,BK-G10,California St at University Ave,BK-D5,37.8584732,-122.2532529,37.86972662872833,...,Berkeley,2025,12,5,11,11,10.95,Non-BART,Weekend,False

In [ ]:
#What columns do I have? I only need a few of these, so I will start to drop stuff.
lyft_data.columns

Index(['field_1', 'ride_id', 'bike_type', 'start_station_name',
       'start_station_id', 'end_station_name', 'end_station_id', 'start_lat',
       'start_lng', 'end_lat', 'end_lng', 'membership', 'start_city',
       'end_city', 'year', 'month', 'weekday', 'start_hour', 'end_hour',
       'trip_duration', 'bart_trip', 'day_type', 'round_trip'],
      dtype='object')

In [ ]:
#create copy not to fuck up my data
lyft_data_copy = lyft_data.copy()

In [ ]:
lyft_data_copy.columns

Index(['field_1', 'ride_id', 'bike_type', 'start_station_name',
       'start_station_id', 'end_station_name', 'end_station_id', 'start_lat',
       'start_lng', 'end_lat', 'end_lng', 'membership', 'start_city',
       'end_city', 'year', 'month', 'weekday', 'start_hour', 'end_hour',
       'trip_duration', 'bart_trip', 'day_type', 'round_trip'],
      dtype='object')

In [ ]:
#What data types do I need to change?
#Like all of them lol
lyft_data_copy.dtypes

field_1               object
ride_id               object
bike_type             object
start_station_name    object
start_station_id      object
end_station_name      object
end_station_id        object
start_lat             object
start_lng             object
end_lat               object
end_lng               object
membership            object
start_city            object
end_city              object
year                  object
month                 object
weekday               object
start_hour            object
end_hour              object
trip_duration         object
bart_trip             object
day_type              object
round_trip            object
dtype: object

In [ ]:
#Drop all unnecessary columns
lyft_data_copy = lyft_data_copy.drop(
    columns=
     ['field_1',
      'end_station_name',
      'end_station_id',
      'end_station_id',
      'end_lat',
      'end_lng',
      'membership',
       'end_city',
      'weekday',
      'start_hour',
      'end_hour',
       'trip_duration',
      'bart_trip',
      'day_type',
      'month',
      'round_trip'
    ]
)

In [ ]:
#Inspect my new data
lyft_data_copy.head()

,ride_id,bike_type,start_station_name,start_station_id,start_lat,start_lng,start_city,year
0,DEED2D13D366AB2E,classic,Market St at 45th St,OK-E2,37.834174,-122.272968,Oakland,2020
1,26A768EB3AF5366C,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020
2,B6C8C77A229092B3,classic,Haste St at College Ave,BK-E10,37.86641794050319,-122.25379943847656,Berkeley,2020
3,8C233FDE4753CFBB,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020
4,56AF44144ED81C62,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020

In [ ]:
#Change the data type for columns for data analysis
lyft_data_copy['start_lat']= lyft_data_copy['start_lat'].astype(float)
lyft_data_copy['start_lng']= lyft_data_copy['start_lng'].astype(float)
lyft_data_copy['year']= pd.to_datetime(lyft_data_copy['year']).dt.year

In [ ]:
#inspect dtypes
lyft_data_copy.dtypes

ride_id                object
bike_type              object
start_station_name     object
start_station_id       object
start_lat             float64
start_lng             float64
start_city             object
year                    int32
dtype: object

# **Geodataframe Conversion**
- Convert my data into geospatial data.
- Set my coordinate reference system.
- Rename Data columns.
- Analyze if changes worked.

In [ ]:
#I need my data points to be in 4326 for consistent spatial analysis across all my data
lyft_gdf = gpd.GeoDataFrame(
    lyft_data_copy,
    geometry = gpd.points_from_xy(lyft_data_copy.start_lng, lyft_data_copy.start_lat),
    crs = "EPSG:4326"
    )

In [ ]:
#My gdf conversion worked, now I can do my geospatial analysis
lyft_gdf

,ride_id,bike_type,start_station_name,start_station_id,start_lat,start_lng,start_city,year,geometry
0,DEED2D13D366AB2E,classic,Market St at 45th St,OK-E2,37.834174,-122.272968,Oakland,2020,POINT (-122.27297 37.83417)
1,26A768EB3AF5366C,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020,POINT (-122.24968 37.80885)
2,B6C8C77A229092B3,classic,Haste St at College Ave,BK-E10,37.866418,-122.253799,Berkeley,2020,POINT (-122.2538 37.86642)
3,8C233FDE4753CFBB,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020,POINT (-122.24968 37.80885)
4,56AF44144ED81C62,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020,POINT (-122.24968 37.80885)
...,...,...,...,...,...,...,...,...,...
952656,99A8D0EF7E5E62D1,electric,Broadway at 30th St,OK-H5,37.819381,-122.261928,Oakland,2025,POINT (-122.26193 37.81938)
952657,E5192258165E74EB,electric,California St at University Ave,BK-D5,37.869727,-122.279389,Berkeley,2025,POINT (-122.27939 37.86973)
952658,E6496153DC9385DC,classic,Russell St at College Ave,BK-G10,37.858473,-122.253253,Berkeley,2025,POINT (-122.25325 37.85847)
952659,A21D1266F4804FC6,electric,Russell St at College Ave,BK-G10,37.858473,-122.253253,Berkeley,2025,POINT (-122.25325 37.85847)
952660,095E1EF0F10BEB44,electric,Russell St at College Ave,BK-G10,37.858473,-122.253253,Berkeley,2025,POINT (-122.25325 37.85847)

In [ ]:
#IDK if this is best practice, but I wanted cleaner station names so I really know what I am looking at
lyft_gdf = lyft_gdf.rename(columns=
                           {'ride_id':'Ride ID',
                            'bike_type':'Bike Type',
                            'start_station_name':'Station Name',
                            'start_station_id': 'Station ID',
                            'start_lat': 'Latitude',
                            'start_lng': 'Longitude',
                            'start_city': 'City',
                            'year': 'Year',
                            'geometry': 'Geometry'
                           })

In [ ]:
#Checking to see if my columns worked
lyft_gdf

,Ride ID,Bike Type,Station Name,Station ID,Latitude,Longitude,City,Year,Geometry
0,DEED2D13D366AB2E,classic,Market St at 45th St,OK-E2,37.834174,-122.272968,Oakland,2020,POINT (-122.27297 37.83417)
1,26A768EB3AF5366C,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020,POINT (-122.24968 37.80885)
2,B6C8C77A229092B3,classic,Haste St at College Ave,BK-E10,37.866418,-122.253799,Berkeley,2020,POINT (-122.2538 37.86642)
3,8C233FDE4753CFBB,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020,POINT (-122.24968 37.80885)
4,56AF44144ED81C62,classic,El Embarcadero at Grand Ave,OK-I9,37.808847,-122.249679,Oakland,2020,POINT (-122.24968 37.80885)
...,...,...,...,...,...,...,...,...,...
952656,99A8D0EF7E5E62D1,electric,Broadway at 30th St,OK-H5,37.819381,-122.261928,Oakland,2025,POINT (-122.26193 37.81938)
952657,E5192258165E74EB,electric,California St at University Ave,BK-D5,37.869727,-122.279389,Berkeley,2025,POINT (-122.27939 37.86973)
952658,E6496153DC9385DC,classic,Russell St at College Ave,BK-G10,37.858473,-122.253253,Berkeley,2025,POINT (-122.25325 37.85847)
952659,A21D1266F4804FC6,electric,Russell St at College Ave,BK-G10,37.858473,-122.253253,Berkeley,2025,POINT (-122.25325 37.85847)
952660,095E1EF0F10BEB44,electric,Russell St at College Ave,BK-G10,37.858473,-122.253253,Berkeley,2025,POINT (-122.25325 37.85847)

In [ ]:
#Created a copy for further analysis
lyft_gdf_copy = lyft_gdf.copy()

# **Transferable Data to Work in Another Notebook**
- Group data.
- Conduct a spatial analysis.
- Prepare a GEOJSON for transfer.to my working notebook.

In [ ]:
#Now the analysis begins
#This is using the groupby function to create a unique station count for each individual station across each year
#Call the new column Trip Count
station_year_counts = (
    lyft_gdf_copy.groupby(["Station ID", "Station Name","City","Year"])
    .size()
    .reset_index(name="Trip Count")
)

In [ ]:
#Lets inspect.
#Looks pretty good to me
#I actually had to fix this but deleted the old code. Basically, I was grouping by geography but the slight changes in coordinates was creating a bunch of unique values so I just used station name instead
station_year_counts

    Station ID                 Station Name      City  Year  Trip Count
0        BK-A3  College Ave at Alcatraz Ave  Berkeley  2020         672
1        BK-A3  College Ave at Alcatraz Ave  Berkeley  2021        1098
2        BK-A3  College Ave at Alcatraz Ave  Berkeley  2022        1106
3        BK-A3  College Ave at Alcatraz Ave  Berkeley  2023        1153
4        BK-A3  College Ave at Alcatraz Ave  Berkeley  2024        1847
..         ...                          ...       ...   ...         ...
742      OK-N6         Webster St at 2nd St   Oakland  2024        2375
743      OK-N6         Webster St at 2nd St   Oakland  2025        2982
744      OK-N7         Webster St at 2nd St   Oakland  2020         689
745      OK-N7         Webster St at 2nd St   Oakland  2021         234
746      OK-N7         Webster St at 2nd St   Oakland  2025         829

[747 rows x 5 columns]

In [ ]:
#Need to add coordinates back into this data
#Using median gives me the average of all the unique station values so I have one, consistent reference point
station_coords = (
    lyft_gdf.groupby(["Station ID", "Station Name"])
    .agg({
        "Latitude": "median",
        "Longitude": "median"
    })
    .reset_index()
)

In [ ]:
#merge them back together so I can have all the data under one variable
station_year_counts = station_year_counts.merge(
    station_coords,
    on=["Station ID", "Station Name"],
    how="left"
)

In [ ]:
#Everything looks really good!
station_year_counts

,Station ID,Station Name,City,Year,Trip Count,Latitude,Longitude
0,BK-A3,College Ave at Alcatraz Ave,Berkeley,2020,672,37.851376,-122.252523
1,BK-A3,College Ave at Alcatraz Ave,Berkeley,2021,1098,37.851376,-122.252523
2,BK-A3,College Ave at Alcatraz Ave,Berkeley,2022,1106,37.851376,-122.252523
3,BK-A3,College Ave at Alcatraz Ave,Berkeley,2023,1153,37.851376,-122.252523
4,BK-A3,College Ave at Alcatraz Ave,Berkeley,2024,1847,37.851376,-122.252523
...,...,...,...,...,...,...,...
742,OK-N6,Webster St at 2nd St,Oakland,2024,2375,37.795195,-122.273970
743,OK-N6,Webster St at 2nd St,Oakland,2025,2982,37.795195,-122.273970
744,OK-N7,Webster St at 2nd St,Oakland,2020,689,37.795194,-122.273969
745,OK-N7,Webster St at 2nd St,Oakland,2021,234,37.795194,-122.273969
746,OK-N7,Webster St at 2nd St,Oakland,2025,829,37.795194,-122.273969

In [ ]:
#Now I am turning into a gdf for analysis
station_year_gdf = gpd.GeoDataFrame(
    station_year_counts,
    geometry=gpd.points_from_xy(
        station_year_counts["Longitude"],
        station_year_counts["Latitude"]
    ),
    crs="EPSG:4326"
)

In [ ]:
#Now I have a geometry column
station_year_gdf

,Station ID,Station Name,City,Year,Trip Count,Latitude,Longitude,geometry
0,BK-A3,College Ave at Alcatraz Ave,Berkeley,2020,672,37.851376,-122.252523,POINT (-122.25252 37.85138)
1,BK-A3,College Ave at Alcatraz Ave,Berkeley,2021,1098,37.851376,-122.252523,POINT (-122.25252 37.85138)
2,BK-A3,College Ave at Alcatraz Ave,Berkeley,2022,1106,37.851376,-122.252523,POINT (-122.25252 37.85138)
3,BK-A3,College Ave at Alcatraz Ave,Berkeley,2023,1153,37.851376,-122.252523,POINT (-122.25252 37.85138)
4,BK-A3,College Ave at Alcatraz Ave,Berkeley,2024,1847,37.851376,-122.252523,POINT (-122.25252 37.85138)
...,...,...,...,...,...,...,...,...
742,OK-N6,Webster St at 2nd St,Oakland,2024,2375,37.795195,-122.273970,POINT (-122.27397 37.79519)
743,OK-N6,Webster St at 2nd St,Oakland,2025,2982,37.795195,-122.273970,POINT (-122.27397 37.79519)
744,OK-N7,Webster St at 2nd St,Oakland,2020,689,37.795194,-122.273969,POINT (-122.27397 37.79519)
745,OK-N7,Webster St at 2nd St,Oakland,2021,234,37.795194,-122.273969,POINT (-122.27397 37.79519)
746,OK-N7,Webster St at 2nd St,Oakland,2025,829,37.795194,-122.273969,POINT (-122.27397 37.79519)

In [ ]:
#I want to see if I have any null values that will mess up my analysis
station_year_gdf[station_year_gdf["Latitude"].isna()]

Empty GeoDataFrame
Columns: [Station ID, Station Name, City, Year, Trip Count, Latitude, Longitude, geometry]
Index: []

In [ ]:
#Just a check
#Does my data have station ids across all years, yes!
station_year_gdf[station_year_gdf["Station ID"] == "BK-A3"]

,Station ID,Station Name,City,Year,Trip Count,Latitude,Longitude,geometry
0,BK-A3,College Ave at Alcatraz Ave,Berkeley,2020,672,37.851376,-122.252523,POINT (-122.25252 37.85138)
1,BK-A3,College Ave at Alcatraz Ave,Berkeley,2021,1098,37.851376,-122.252523,POINT (-122.25252 37.85138)
2,BK-A3,College Ave at Alcatraz Ave,Berkeley,2022,1106,37.851376,-122.252523,POINT (-122.25252 37.85138)
3,BK-A3,College Ave at Alcatraz Ave,Berkeley,2023,1153,37.851376,-122.252523,POINT (-122.25252 37.85138)
4,BK-A3,College Ave at Alcatraz Ave,Berkeley,2024,1847,37.851376,-122.252523,POINT (-122.25252 37.85138)
5,BK-A3,College Ave at Alcatraz Ave,Berkeley,2025,1499,37.851376,-122.252523,POINT (-122.25252 37.85138)

In [ ]:
#Getting my GEOJSON to import data to my other notebook
output_geojson = os.path.join(DATA_DIR, "station_year_counts.geojson")

station_year_gdf.to_file(output_geojson, driver="GeoJSON")

print(f"File saved to: {output_geojson}")

In [ ]:
#check
print("Saved to:", os.path.join(DATA_DIR, "station_year_counts.geojson"))